version: '3'
services:
  ubuntu1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu1
    tty: true
    networks:
      - mynetwork
  ubuntu2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu2
    tty: true
    networks:
      - mynetwork
  ubuntu3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu3
    tty: true
    networks:
      - mynetwork
  ubuntu4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu4
    tty: true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

